//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using interopservices = System.Runtime.InteropServices;
using simulated = Microsoft.Robotics.Services.KHR1.Simulated.Proxy;

[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="SimulatedKHR1.Y2006.M07, Version=0.0.0.0, Culture=neutral, PublicKeyToken=adf1b61" +
    "0070c42f4")]
[assembly: System.Security.Permissions.SecurityPermissionAttribute(System.Security.Permissions.SecurityAction.RequestMinimum, Flags=System.Security.Permissions.SecurityPermissionFlag.Execution)]
[assembly: System.Security.Permissions.SecurityPermissionAttribute(System.Security.Permissions.SecurityAction.RequestOptional)]
[assembly: System.Security.AllowPartiallyTrustedCallersAttribute()]
[assembly: ContractNamespace(simulated.Contract.Namespace, ClrNamespace="Microsoft.Robotics.Services.KHR1.Simulated.Proxy")]
[assembly: ContractNamespace(simulated.Contract.Namespace, ClrNamespace="Microsoft.Robotics.Services.KHR1.Simulated.Proxy")]
[assembly: interopservices.ComVisible(true)]


